# Introduction to Computer Programming and Numerical Methods

> **Mohamad M. Hallal, PhD** <br> Teaching Professor, UC Berkeley

[![License](https://img.shields.io/badge/license-CC%20BY--NC--ND%204.0-blue)](https://creativecommons.org/licenses/by-nc-nd/4.0/)
***

# MATLAB

1. [**Syntax Differences Between MATLAB and Python**](#s1)
2. [**MATLAB Basics**](#s2)
3. [**Data Structures**](#s3)
4. [**Functions**](#s4)
5. [**Conditional Statements**](#s5)
6. [**Iteration**](#s6)

***

# 0. Motivation

Many engineers and scientists use MATLAB to analyze and design systems and products. MATLAB is primarily designed for numerical and matrix-based computation. There are many similarities between MATLAB and Python, so your Python experience will provide a good head start for learning MATLAB. However, there are important differences that you must learn to switch effectively from Python to MATLAB. In this section, we will explore basic MATLAB syntax concepts and demonstrate equivalent concepts in Python to ease the transition. Our goal is to highlight the MATLAB approach to topics you are already familiar with in Python.

**Learning objectives:**

* Evaluate the syntax differences between Python and MATLAB
* Set up a MATLAB environment that replicates the majority of Python functions
* Convert scripts from Python to MATLAB
* Avoid common issues when transitioning from Python to MATLAB

# 1. Syntax Differences Between MATLAB and Python <a id="s1"></a>

Understanding the syntax differences between MATLAB and Python is crucial for a seamless transition between the two languages. While the fundamental logic behind most operations remains similar, each language has unique coding approaches due to their core design philosophies. MATLAB, short for "MATrix LABoratory," treats everything as a matrix, whereas Python treats everything as a general object.

For instance, in MATLAB, strings are treated as matrices of characters or as arrays of strings, while in Python, strings have their own type called `str`.

This section presents key syntax differences that you are likely to encounter. These examples also demonstrate some basic MATLAB language features.

## 1.1. Comments

In Python, comments are created using the hash or pound sign (`#`). In MATLAB, comments are created using the percent sign (`%`) on a line. Both interpreters ignore the content of comments.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
# This is a single line comment
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
% This is a single line comment
```

In Python, multi-line comments can be created using triple quotes (`'''`).  In MATLAB, multi-line comments start with `%{` and end with `%}`. Note that `%{` and `%}` should be on their own lines (i.e., there should be nothing after `%{` and nothing before `%}` on the same line).

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
'''This is a multi-line comment
Line 2
Line 3'''
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
%{
This is a multi-line comment
Line 2
Line 3
%}
```

## 1.2. Semicolons to End Lines in MATLAB

In MATLAB, by default, executing a statement displays the result in the Command Window, which can be useful for interactive sessions. However, this behavior might be undesirable in certain situations. To suppress the display of output, simply end each statement with a semicolon (`;`).

In Python, ending lines of code with semicolons doesn't change the behavior since Python doesn't use them to suppress or display output. 

So in Python, you must explicitly print something when you want to display its value, whereas in MATLAB, you must explicitly silence something instead of explicitly displaying it. This contrast illustrates the differing default behaviors between the two languages.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
x = 1
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
x = 1;

```

<div class="alert alert-block alert-success"> <b>TIP!</b> Most of the time you should suppress code output by using a semicolon at the end of all assignment statements in MATLAB.</div>


## 1.3. Displaying Output

Although omitting the semicolon from the end of an expression is one way to display output in MATLAB, the `disp()` function can be used to explicitly display the value of variables or expressions in the Command Window. This function is similar to Python's `print()` function. In addition to `disp()`, MATLAB offers other functions for displaying output and formatting it, which we will discuss in more detail later.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
x = 1
print(x)
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
x = 1;
disp(x)
```

## 1.4. Indentation versus `end`

Python uses indentation (whitespace) to define code blocks within functions, if statements, loops, and other control structures. Thus, indentation is required in Python. In contrast, MATLAB employs the `end` keyword to delineate code blocks that belong to function definitions, if statements, and loops. While indentation is not syntactically necessary in MATLAB, it is highly recommended for better code readability. 

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
if x == 1:
    print(x)
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```OCTAVE
% Not recommended, but works fine
if x == 1
disp(x)
end

% Recommended
if x == 1
    disp(x)
end
```

<div class="alert alert-block alert-warning"> <b>NOTE!</b> The <code>end</code> keyword is crucial, as it is the only way MATLAB knows which code blocks belong to a function, loop, if statement, and other control structures.</div>

In Python, a colon (`:`) is used to indicate the start of an indented code block (after a function definition, if statement, loop, etc.). In MATLAB, colons should not be used to indicate code blocks; doing so will result in an error.

## 1.5. Indexing

MATLAB uses 1-based indexing, meaning arrays and matrices start with an index of 1. Python, on the other hand, uses 0-based indexing, with arrays and lists starting at index 0. This difference can lead to off-by-one errors when transitioning between the two languages.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
arr = [10, 20, 30]
first_element = arr[0]
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```OCTAVE
arr = [10, 20, 30];
first_element = arr(1);
```

<div class="alert alert-block alert-warning"> <b>NOTE!</b> Python uses square brackets for indexing: <code>arr[index]</code>. However, MATLAB uses parentheses for indexing: <code>arr(index)</code>.</div>

# 2. MATLAB Basics <a id="s2"></a>

## 2.1. Arithmetic Operations

Most mathematical operators in MATLAB are the same as those in Python, with the exception of exponentiation, quotient, and modulo. Specifically, exponentiation is achieved using `^` in MATLAB, while the quotient and remainder are obtained using functions rather than operators. 

| Operation           | Mathematical Notation                | Python  | MATLAB           |
|:--------------------|:------------------------------------:|:-------:|:-----------------|
| Addition            | $a+b$                                | `a + b` | `a + b`          |
| Subtraction         | $a-b$                                | `a - b` | `a - b`          |
| Multiplication      | $a\times b$                          | `a * b` | `a * b`          |
| Division            | $a\div b$                            | `a / b` | `a / b`          |
| Exponentiation      | $a^b$                                | `a ** b`| `a ^ b`          |
| Quotient            | $\left\lfloor a\div b \right\rfloor$ | `a // b`| `floorDiv(a, b)` |
| Remainder or Modulo | $a\%b$                               | `a % b` | `mod(a, b)`      |

## 2.2. Order of Operations

Similar to Python, MATLAB follows the standard order of operations: powers are executed before multiplication and division, which are executed before addition and subtraction.

## 2.3. Trigonometry, Logarithms, and Other Operations

One of MATLAB's strengths lies in its extensive library of built-in functions for mathematical operations, making it particularly useful for scientific and engineering tasks. Unlike Python, where you often need to import external libraries for mathematical functions, MATLAB provides a comprehensive set of these functions by default. A complete list of mathematical functions and constants in MATLAB can be found in the [MATLAB documentation](https://www.mathworks.com/help/matlab/elementary-math.html).

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
import math
math.log10(10)
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```
log10(10)
```

***

You can get help on a function in MATLAB by simply typing `help` followed by the function's name.

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```
help log10
```

***

MATLAB also includes constants (e.g., $\pi$ ). These are also built-in and can be used directly.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
import math
math.pi
math.inf
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```
pi
Inf
```
***

The table below shows some of the available mathematical functions in MATLAB. The full list an be found in the [MATLAB documentation](https://www.mathworks.com/help/matlab/elementary-math.html).

| Operation                              | MATLAB Notation |
| :------------------------------------- | :-------------- |
| Sine of an angle in radians            | `sin()`         |
| Sine of an angle in degrees            | `sind()`        |
| Arcsine in radians                     | `asin()`        |
| Arcsine in degrees                     | `asind()`       |
| Angle from degrees to radians          | `deg2rad()`     |
| Natural logarithm ($ln$ or $log_e$)    | `log()`         |
| Logarithm (base 10)                    | `log10()`       |
| Exponential                            | `exp()`         |
| Square root                            | `sqrt()`        |

## 2.4. Overflow and Undefined Results

In mathematical computations, it's crucial to be aware of how MATLAB and Python handle special cases such as division by zero and the representation of infinity. In Python, dividing by zero results in a runtime error. In contrast, MATLAB handles division by zero differently. When you divide a nonzero number by zero in MATLAB, the result is represented as `Inf` (infinity).

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
import math

a = 1 / 0          # Error
b = 1 / math.inf   # 0.0
c = 0 * math.inf   # nan
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```OCTAVE
a = 1 / 0          % Inf
b = 1 / Inf        % 0.0
c = 0 * Inf        % NaN
```

## 2.5. Basic Data Types

Both Python and MATLAB support scalar data types, which represent single values (not arrays or collections). In Python, common scalar data types include `int`, `float`, `bool`, and `complex`.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
a = 5
print(type(a))   # Displays <class 'int'>

b = int(5.0)   
print(type(b))   # Displays <class 'float'>

c = 5 > 3        # c is True
print(type(c))   # Displays <class 'bool'>
```

MATLAB has different scalar data types. For example, float data type is called `double` in MATLAB. MATLAB stores all numbers by default as class `double`, which refers to double precision floating point numbers. To create an integer one needs to explicitly create or convert a variable to an integer.

| Class                         | Description                         |
|:------------------------------|:------------------------------------|
| double                        | double-precision float              |
| single                        | single-precision float              |
| uint8, uint16, uint32, uint64 | Unsigned 8, 16, 32, 64-bit integer  |
| int8, int16, int32, int64     | Signed 8, 16, 32, 64-bit integer    |
| logical                       | 	Boolean values `1` and `0`        |

To get the type of a variable in MATLAB, use the `class()` function. You can also convert between different data types using built-in functions.

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
a = 5;
class(a)         % Displays 'double'

a = 5.0;
class(a)         % Displays 'double'

b = int32(5.0);
class(b)         % Displays 'int32'

c = 5 > 3;       % c is logical 1
class(c)         % Displays 'logical'
```

<div class="alert alert-block alert-warning"> <b>NOTE!</b> In MATLAB, true is represented as logical 1 and false as logical 0.</div>

## 2.6 Variables

Variables work in a similar way in Python and MATLAB. Note that MATLAB does not support short notations like `+=` for assignment addition operator.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
a = 5
a = a + 5      # a is now 10 (can also use a += 5)
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```OCTAVE
a = 5;
a = a + 5;     % a is now 10 (cannot use a += 5)
```

## 2.7. Managing Variables

In MATLAB, the `clc` and `clear` commands help manage the command window and workspace.
* `clc` clears the command window display, effectively removing all previous commands and output
* `clear` clears variables from the workspace, freeing up memory

These commands are useful for keeping your MATLAB environment organized.

## 2.8. Logical Expressions and Operators

MATLAB uses the same comparison operators as Python, except for the "not equal" operator. In MATLAB, a tilde `~` is used for negation in comparison operators, whereas Python uses an exclamation mark `!`.

| Comparison         | Python  | MATLAB | 
|:-------------------|:------  |:-------|
| Less than          | `<`     | `<`    |
| Greater than       | `>`     | `>`    | 
| Less than or equal | `<=`    | `<=`   | 
| Greater or equal   | `>=`    | `>=`   | 
| Equal              | `==`    | `==`   | 
| Not equal          | `!=`    | `~=`   |

Both MATLAB and Python provide logical operators, but the symbols differ.

| Operation     | Python  | MATLAB |
|:--------------|:------- |:-------|
| AND           | `and`   | `&`   |
| OR            | `or`    | `\|` |
| NOT           | `not`   | `~`    |

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
a = (5 > 3) and (1 > 1)   # a is False
b = (5 > 3) or (1 > 1)    # b is True
c = not b                 # c is False
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```OCTAVE
a = (5 > 3) & (1 > 1);    % a is logical 0
b = (5 > 3) | (1 > 1);    % b is logical 1
c = ~b;                   % c is logical 0
```

<div class="alert alert-block alert-warning"> <b>NOTE!</b> When evaluating scalar logical expressions, it is recommended to use <code>&&</code> and <code>||</code> instead of <code>&</code> and <code>|</code> for logical operators. These are known as short-circuit logical operators and are more efficient. For example the <code>&&</code> operator stops evaluating as soon as the result is determined. If the first operand is false, the second operand is not evaluated because, regardless of its result, the final outcome will be false. This can save time and computational resources. However, the <code>&&</code> and <code>||</code> operators can only be used with scalar values. They cannot be used with arrays. For element-wise logical operations on arrays, the <code>&</code> and <code>|</code> operators should be used.</div>

# 3. Data Structures <a id="s3"></a>

Both MATLAB and Python provide various data structures (non-scalar data types) for organizing and manipulating data efficiently. While Python includes `str`, `list`, `tuple`, and `ndarray`, MATLAB primarily revolves around arrays and matrices. 

## 3.1. Double Arrays

MATLAB's primary data structure is the numeric array, which is essentially a matrix. MATLAB arrays resemble most closely NumPy arrays in Python.

### 3.1.1. Creating Arrays

Arrays in MATLAB are formed using square brackets `[ ]` and the values in the same row are separated by commas (`,`) or whitespace and the rows are separated by a semicolon (`;`). Below are some examples of 1-D and 2-D arrays in Python and MATLAB.

$$
A = 
\begin{bmatrix} 
2.1 & 3.4 & 9.3
\end{bmatrix} \ \ \ \ \ \ \
B = 
\begin{bmatrix} 
2.1\\ 
3.4\\
9.3
\end{bmatrix}
$$

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
A = np.array([[2.1, 3.4, 9.3]]) # commas ',' inside the same square bracket '[]' to separate columns

B = np.array([[2.1], 
              [3.4], 
              [9.3]]) # separate square brackets '[]' for each row and commas ',' between square brackets
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
A = [2.1, 3.4, 9.3]  % commas ',' to separate columns (optional). Can also use A = [2.1 3.4 9.3]

B = [2.1; 3.4; 9.3]  % semicolons ';' to separate rows (required)
```

$$
C = 
\begin{bmatrix} 
2.1 & 3.4 & 9.3\\ 
9.2 & -2.7 & 4.0
\end{bmatrix}  \ \ \ \ \ \ \
D = 
\begin{bmatrix} 
2.1 & 9.2\\ 
3.4 & -2.7\\
9.3 & 4.0
\end{bmatrix}
$$

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
C = np.array([[2.1, 3.4, 9.3],
              [9.2, -2.7, 4.0]])

D = np.array([[2.1, 9.2], 
              [3.4, -2.7], 
              [9.3, 4.0]])
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
C = [2.1, 3.4, 9.3; 9.2, -2.7, 4.0]

D = [2.1, 9.2; 3.4, -2.7; 9.3, 4.0]

```

### 3.1.2. Creating Arrays with Pattern

Similar to Python, we can create arrays that have a specific pattern in MATLAB. For generating arrays that are in order with a constant spacing, it is useful to use the colon operator, `:`, which has the following syntax:

```
array = start : step : end
```

If a `step` is not specified, MATLAB will use a default value of 1. So, `1:1:100` and `1:100` are equivalent. Negative or non-integer increments can also be used.

The `start` value should always be specific and does not have a default value.

Note that this syntax is similar to Python's `np.arange(start, end, step)`. However, the order of `end` and `step` is switched and  `end` is excluded in Python, but it is included in MATLAB.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
>>> array = np.arange(0, 10, 2)
>>> print(array)

[0 2 4 6 8]
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> array = 0:2:10

array =

     0     2     4     6     8    10
```

***

For generating arrays that have a certain number of evenly spaced points between a start and end value, it is useful to use the `linspace()` function, which is very similar to NumPy's `np.linspace(start, end, num)`:

```
array = linspace(start, end, num)
```

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
>>> array = np.linspace(0, 10, 5)
>>> print(array)

[ 0. ,  2.5,  5. ,  7.5, 10. ]
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> array = linspace(0, 10, 5)

array =

     0    2.5000    5.0000    7.5000   10.0000
```

***

There are also predefined arrays that can be useful. For example, the `zeros()` and `ones()` functions, which are similar to `np.zeros()` and `np.ones()`. In NumPy, the shape of the matrix `(n_rows, n_cols)` is give as a single argument in the form of a tuple (e.g., `np.zeros((3, 5))`), whereas in MATLAB, the function takes two arguments, the first is for the number of rows and the second is for the number of columns (e.g., `zeros(3, 5)`). 

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
>>> array = np.ones((3, 5))
>>> print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> array = ones(3, 5)

array =

     1     1     1     1     1
     1     1     1     1     1
     1     1     1     1     1
```

### 3.1.3. Array Properties

In linear algebra, array properties or attributes refer to specific characteristics associated with an array that provide essential information about its size, structure, and behavior. Below are some of the common array properties and the syntax that can be used to obtain them in Python and MATLAB. The results below are based on the following matrix:

$$
C = 
\begin{bmatrix} 
2.1 & 3.4 & 9.3\\ 
9.2 & -2.7 & 4.0
\end{bmatrix}
$$

| Property                    | Python Example | Python Output | MATLAB Example | MATLAB Output |
| :-------------------------- | :------------- | :------------ | :------------- | :------------ |
| Number of dimensions        | `C.ndim`       | `2`           | `ndims(C)`     | `2`           |
| Length in each dimension    | `C.shape`      | `(2, 3)`      | `size(C)`      | `[2 3]`       | 
| Total number of elements    | `C.size`       | `6`           | `numel(C)`     | `6`           |
| Length of largest dimension | N/A            | N/A           | `length(C)`    | `3`           |

where `C` is the array name

<div class="alert alert-block alert-warning"> <b>NOTE!</b> The built-in Python function <code>len()</code> is NOT the same as MATLAB's <code>length()</code> function. The <code>len()</code> function in Python returns the number of items in an object. However, the <code>length()</code> function in MATLAB returns the largest dimension of an array. If you want the total number of elements in an array in MATLAB, you should use <code>numel()</code>.</div>

### 3.1.4. Indexing

Python uses square brackets for indexing: `array[index]`. However, MATLAB uses parentheses for indexing: `array(index)`. Also, as previously mentioned, indexing in Python starts at 0, whereas indexing in MATLAB starts at 1.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
>>> A = np.array([2.1, 3.4, 9.3]) 
>>> A[0]

2.1
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> A = [2.1, 3.4, 9.3];
>> A(1)

ans =

    2.1000
```

You can also index 2-D arrays using `array[row_index, column_index]` in Python and `array(row_index, column_index)` in MATLAB.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
>>> C = np.array([[2.1, 3.4, 9.3],
                  [9.2, -2.7, 4.0]])
>>> C[1, 2]

4.0
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> C = [2.1, 3.4, 9.3; 9.2, -2.7, 4.0];
>> C(1, 2)

ans =

    3.4000
```

***

Unlike Python, MATLAB does not have negative indexing. Nonetheless, the last element of an array can be accessed using the keyword `end` in MATLAB.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
>>> C = np.array([[2.1, 3.4, 9.3],
                  [9.2, -2.7, 4.0]])
>>> C[-1, -1]

4.0
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> C = [2.1, 3.4, 9.3; 9.2, -2.7, 4.0];
>> C(end, end)

ans =

    4
```

### 3.1.5. Slicing

In Python, slicing an `ndarray` is done with the syntax `array[start:end:step]`. In MATLAB, the slicing syntax is `array(start:step:end)`. Note that:
* The order of `end` and `step` is switched
* The `end` index is excluded in Python, but it is included in MATLAB
* The `start` index can be omitted in Python (defaults to the beginning of the array) but cannot be omitted in MATLAB.


$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
>>> arr = np.arange(9)   # [0, 1, 2, 3, 4, 5, 6, 7, 8]
>>> arr[:8:2]            # If you omit start, slicing will start from the first index by default

[0, 2, 4, 6]
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> arr = 0:8;            % [0, 1, 2, 3, 4, 5, 6, 7, 8]
>> arr(1:2:9)            % You cannot omit start in MATLAB, even if it is the first index

ans =

     0     2     4     6     8
```

Another way to index multiple elements in both Python and MATLAB is using an array of indexes.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
>>> C = np.array([[2.1, 3.4, 9.3],
                  [9.2, -2.7, 4.0]])
>>> C[0, [0, 2]]

array([2.1, 9.3])
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> C = [2.1, 3.4, 9.3; 9.2, -2.7, 4.0];
>> C(1, [1, 3])

ans =

    2.1000    9.3000
```

### 3.1.6. Array Manipulation

In Python, square brackets are used for lists, which are not primarily meant for mathematical and numerical calculations. For instance, `[1, 2] + [3, 4]` will concatenate the lists and return `[1, 2, 3, 4]`. However, in MATLAB, the default data type is a double array, and using `[1, 2] + [3, 4]` will perform mathematical addition, yielding `[4, 6]`.

To concatenate arrays in MATLAB, you should enclose them in square brackets `[]` and separate them by either commas `,` for horizontal concatenation or semicolons `;` for vertical concatenation. It's important to note that the arrays being concatenated must have consistent dimensions for successful concatenation.

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> A = [1, 2];
>> B = [3, 4];
>> [A, B]         % concatenate horizontally in the same row using ,

ans =

     1     2     3     4
 
>> [A; B]        % concatenate vertically in different rows using ;

ans =

     1     2
     3     4
```

### 3.1.7. Array Operations

Basic arithmetic between an array and a scalar works similarly in MATLAB and Python's NumPy arrays, with a notable exception being exponentiation. If $c$ is a scalar, and $A$ is an array, the following operations apply using MATLAB syntax:

* `A + c`: adds $c$ to every element of $A$ 
* `A − c`: subtracts $c$ from every element of $A$
* `A * c`: multiplies every element of $A$ by $c$
* `A / c`: divides every element of $A$ by $c$

<div class="alert alert-block alert-warning"> <b>NOTE!</b> Unlike Python, you cannot use <code>A ^ c</code> to raise every element of $A$ to the power $c$. This will result in error, unless $A$ is a square matrix. Instead you have to use <code>A .^ c</code>. See below for more details.</div>

When performing arithmetic operations between two arrays, there are differences between MATLAB and Python. In Python's NumPy, mathematical operators result in element-wise operations if the arrays are of the same shape. In MATLAB, however, a dot `.` is required before certain operators to perform element-wise operations, specifically `*`, `/`, and `^`. These operations are only defined if the two arrays are of the **same shape**. Consider two arrays $A1$ and $A2$ of the same shape:

* `A1 + A2`: takes every element of $A1$ and adds it to the corresponding element of $A2$ in the same index
* `A1 - A2`: takes every element of $A2$ and subtracts it from the corresponding element of $A1$ in the same index
* `A1 .* A2`: takes every element of $A1$ and multiplies it by the corresponding element of $A2$ in the same index
* `A1 ./ A2`: takes every element of $A1$ and divides it by the corresponding element of $A2$ in the same index
* `A1 .^ A2`: takes every element of $A1$ and raises it to the power the corresponding element of $A2$ in the same index

<div class="alert alert-block alert-warning"> <b>NOTE!</b> If you run <code>A1 * A2</code> in MATLAB, this will perform standard array multiplication, which is different from element-by-element multiplication. This will be discussed in greater detail later in the course.</div>

<div class="alert alert-block alert-success"> <b>NOTE!</b> It might be easier to always add a dot <code>.</code> when performing multiplication, division, or exponentiation on an array, as this will work for both array-scalar and array-array operations. Only if you want to perform standard matrix multiplication, do not include the dot.</div>

All of MATLAB’s built-in arithmetic functions, such as `sin()`, can take arrays as input arguments. The output is the function evaluated for every element of the input array.

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```ocatve
>> A = [1, 4, 9, 25];
>> sqrt(A)

ans =

     1     2     3     5
```

***

Comparison operations on arrays work very similarly in Python and MATLAB. The output is an array of the same shape as the original array, containing `True` or `False` (in Python) or `1` or `0` (in MATLAB) based on the result of the comparison for each element.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
>>> A = np.array([2.1, 3.4, 9.3]) 
>>> A > 3

[False,  True,  True]
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> A = [2.1, 3.4, 9.3];
>> A > 3

ans =

  1×3 logical array

   0   1   1
```
***

To perform element-wise logical operations, you will have to use `&` for logical AND and `|` for logical OR. The output is an array of the same shape as the original arrays, containing `True` or `False` (in Python) or `1` or `0` (in MATLAB) based on the result of the comparison for each corresponding pair of elements in the same position.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
>>> A = np.array([2.1, 3.4, 9.3]) 
>>> np.logical_and(A > 2, A < 5)

[True,  True,  False]
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> A = [2.1, 3.4, 9.3];
>> A > 2 & A < 5

ans =

  1×3 logical array

   1   1   0
```

***

Similar to Python, MATLAB can index elements of an array that satisfy a logical expression. Instead of giving the values of the indexes, a logical expression can be used directly to filter the elements of the array.

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> A = [2.1, 3.4, 9.3];
>> A(A > 3) = -1         % index the values of A that are greater than 3 and reassign them the value -1

A =

    2.1000   -1.0000   -1.0000
```

### 3.1.8. MATLAB Functions on Arrays

MATLAB has many functions that operate on arrays, some of which are shown below. The full list an be found in the [MATLAB documentation](https://www.mathworks.com/help/matlab/referencelist.html?type=function&category=descriptive-statistics&s_tid=CRUX_topnav).

| Operation                              | MATLAB Notation |
| :------------------------------------- | :-------------- |
| Sum of all elements                    | `sum()`         |
| Minimum of all elements                | `min()`         |
| Maximum of all elements                | `max()`         |
| Average of all elements                | `mean()`         |

## 3.2. `char` Arrays

Similar to Python's `str`, MATLAB has a data type for storing alphanumeric characters, which is called `char`. `char` data types are assembled using single quotes `' '` on both sides, but brackets can also be used to concatenate strings. Similar to Python, you can index `char` data types in MATLAB, as they are considered an array of characters.

<div class="alert alert-block alert-warning"> <b>NOTE!</b> Unlike Python, MATLAB only accepts single quotes <code>'</code> for <code>char</code> arrays. If you use double quotes <code>"</code>, this creates a different data type known as <code>string</code>. In MATLAB, you cannot directly index individual characters of <code>string</code> (the entire string is treated as a single object which cannot be subdivided into individual characters) like you can with <code>char</code> arrays. </div>

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> greeting1 = 'Welcome to E7!';
>> greeting2 = ['W', 'e', 'l', 'c', 'o', 'm', 'e', ' ', 't', 'o', ' ', 'E', '7', '!']; % same as greeting1
>> greeting2(12:13)

ans =

    'E7'

>> class(greeting2)

ans =

    'char'
```
***

To include an apostrophe (single quotation mark) within a `char` array in MATLAB, you can use two consecutive single quotation marks (`''`) – this will add a single apostrophe.

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```
>> advice = 'Don''t cheat, it''s not worth the consequences.'

advice =

    'Don't cheat, it's not worth the consequences.'
```

***

We saw that `str` in Python are immutable. However, `char` arrays in MATLAB are mutable, meaning, you can modify individual characters in a `char` array.

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> s1 = 'Thix xtring hax xome obvioux typox';
>> s1(s1 == 'x') = 's'

s1 =

    'This string has some obvious typos'
```

***

To format strings in MATLAB, we can use the `sprintf()` function.

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> sprintf('Welcome to %s. There are %d students in the class.', 'E7', 400)

ans =

    'Welcome to E7. There are 400 students in the class.'
```

The following specifiers can be used inside `sprintf()`:
* `%s`: used to insert a string into the formatted string
* `%d`: used to insert an integer into the formatted string
* `%f`: used to insert a floating-point number into the formatted string
    > You can control the precision of decimal digits by using a format like `%.2f`, which will present two decimal places in the output.
* `%e`: used to insert a number in scientific notation into the formatted string

## 3.3. Cell Arrays

In MATLAB, cell arrays can include elements of different data types. They are defined using curly braces `{ }`. Not only are cell arrays defined using braces, but they are also indexed using braces. If you index cell arrays using parentheses, you will get another cell array containing the contents of the indexed elements.

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> cell_array = {1, 2, 3, 'four'}
>> class(cell_array)

ans =

    'cell'
    
>> cell_array{4} % index using curly braces

ans =

    'four'
    
>> cell_array(4) % index using parentheses. You get another cell array.

ans =

  1×1 cell array

    {'four'}
    
```

## 3.4. Membership Operator

MATLAB does not have a built-in `in` operator like Python. However, you can achieve similar functionality in MATLAB using various methods. One method is to use the `ismember(element, array)` function, which checks if `element` is in `array`. 

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> array = [1, 2, 3, 4, 5, 1];
>> ismember(1, array)

ans =

  logical

   1
```

# 4. Functions <a id="s4"></a>

Custom functions in Python and MATLAB serve similar purposes in terms of encapsulating reusable code, but there are differences in how you define and use them due to the programming languages' distinct syntax and paradigms. Below is a comparison of the major components of a function in Python and MATLAB.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
def my_function(arg1, arg2):
    '''
    Description
    '''
    # function body
    return result
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
function [result] = my_function(arg1, arg2)
    %{
    Description
    %}
    % function body
end
```

| Function Component  | Python                                    | MATLAB                                                |
| :------------------ | :---------------------------------------- | :---------------------------------------------------- |
| Function definition | `def` keyword, line ends with `:`         | `function` keyword, should not end line with `:`      |
| Output parameters   | After `return` statement                  | Inside `[ ]`, after `function`                        |
| Documentation       | Docstring using triple quotes `'''`       | Single (`%`) or multi-line comment (`%{ %}`)          |

<div class="alert alert-block alert-warning"> <b>NOTE!</b> In MATLAB, both the return parameters (output arguments) and input arguments are typically defined in the function header. The output arguments are listed after the keyword <code>function</code> inside square brackets and the input arguments are listed after the function's name inside parentheses. When the function execution ends (either by reaching the end of the function or by being terminated early), MATLAB returns the final values of the output arguments listed between square brackets.</div>

<div class="alert alert-block alert-warning"> <b>NOTE!</b> If there is only one output, square brackets are optional but still allowed. So, for the above example, both <code>function result = my_function(arg1, arg2)</code> and <code>function [result] = my_function(arg1, arg2)</code> could be used to define the function since there is only one output.</div>

The concepts of local and global scope work in the exact same way in Python and MATLAB. Below, we discuss some other differences between functions in Python and MATLAB.

To program your own functions in MATLAB, you will need to use a new part of the MATLAB environment called
the editor. The editor allows you to build, edit, and save your functions. Once the function is completed, you will need to save it. Click the save button, in the upper left-hand corner of the editor. **When prompted to name the file, the filename must have the same name as the function name.** The file type should be .m, an m-file, which is the standard file type for MATLAB functions.

## 4.1. Indentation and the `end` Keyword

Unlike Python, indenting the function's body in MATLAB is not required, but it is still recommended for better readability.

In MATLAB, the keyword `end` is placed at the end of the function. In this case, it denotes the end of a function. Although some functions will still work if `end` is omitted, it is good practice to end a function with the keyword `end`. Specifically, `end` is required when defining multiple or nested functions in the same file.

## 4.2. Default Arguments

MATLAB does not support default arguments inside the function definition. For example, `my_function(arg1=def_val1, arg2=def_val2)` will result in an error in MATLAB. It is still possible to assign default arguments in MATLAB, but this should be done in the function's body. You can check the [following post](https://blogs.mathworks.com/loren/2009/05/05/nice-way-to-set-function-defaults/) for more details.

## 4.3. Calling Functions

Python and MATLAB use very similar syntax to call functions. A function is called by using its name followed by parentheses, and input arguments are placed within those parentheses. Python returns multiple parameters as a tuple. However, MATLAB returns each value separately. So, if you make fewer assignments than there are output variables, MATLAB will only assign the first values and the rest will be dropped.

*Consider the following function in MATLAB:*

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
function [result1, result2] = my_sum(a, b, c)
    result1 = a + b;
    result2 = b + c;
end
```

***

*If you call the function and assign the function call to one variable, only the first parameter will be returned. MATLAB will not return both as an array.* 

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> out1 = my_sum(1, 2, 3) % MATLAB will only retrun the first value, result1

out1 =

     3
```

***

*To return multiple parameters, assign the function call to an array of variable inside `[ ]`:* 

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
>> [out1, out2] = my_sum(1, 2, 3) % MATLAB will return both values

out1 =

     3


out2 =

     5
```

## 4.4. Multiple Outputs

When a function definition has multiple outputs in MATLAB, all of these outputs should be defined inside the function's body. Failure to define an output inside the function may result in errors.

In the example below, `result2` is not defined inside the function's body. This will result in an error if you try to call the function and assign the output to multiple variables using `[result1, result2] = my_sum(a, b, c)`. 

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
function [result1, result2] = my_sum(a, b, c)
    result1 = a + b;
end
```

```octave
>> [out1, out2] = my_sum(1, 2, 3)

Error using my_sum
Too many output arguments.
```

## 4.5. `return` Statement

Although MATLAB does not use the `return` keyword to return output parameters, this keyword can be used to terminate a function early if certain conditions are met. If any of the output arguments have not been defined when a `return` statement is reached, you may get an error. Note that in MATLAB, the `return` keyword should not be followed by anything. It is only used to force immediate exit from the function, similar to how `break` forces immediate exit from a loop. However, `break` can only be used in a loop and cannot be used to terminate a function.

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
function [result1, result2] = my_sum(a, b, c)
    result1 = a + b;
    result2 = b + c;
    if result1 > result2
        return            % If result1 is greater than result2, exit the function immediately
    else
        result2 = a + b;  % This line will not be executed if result1 > result2
    end
end
```

In the above example, if `result1 > result2` is true, the code will enter the if branch and run `return`. This will force immediate exit from the function, and any remaining code inside the function will be ignored.

## 4.6. Anonymous Functions

Recall that lambda function can be defined in Python using the following syntax:

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
function_name = lambda argument_1, argument_2, ... : expression 
```

***

MATLAB supports anonymous functions in a way that is similar to Python. To create an anonymous function in MATLAB, the following syntax can be used:

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
function_name = @(argument_1, argument_2, ...) expression ;
```

# 5. Conditional Statements <a id="s5"></a>

Conditional statements works similarly in Python and MATLAB, but there are some differences in the syntax. For example, MATLAB uses `elseif` instead of Python's `elif`. Also, no colon `:` should be included at the end of each `if`, `elseif`, and `else` statement. In addition, while indentation is not required in MATLAB, it is recommended for better readability. Lastly, you should use the keyword `end` to specify the end of an `if`/`elseif`/`else` block.

## 5.1. If Statements

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
if condition:
    # do code block
# subsequent code
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
if condition
    % do code block (indentation not required but recommended)
end
% subsequent code
```

<div class="alert alert-block alert-success"> <b>TIP!</b> When you forget to include <code>end</code> at the end of an <code>if</code> statement, MATLAB will generate an error. So, whenever you start an <code>if</code> statement, also write the <code>end</code> immediately, and then fill in between. This will help you keep track of your code when it becomes more complicated.</div>

## 5.2. If-Else Statements

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
if condition:
    # do code block 1
else:
    # do code block 2
# subsequent code
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
if condition
    % do code block 1 (indentation not required but recommended)
else
    % do code block 2 (indentation not required but recommended)
end
% subsequent code
```

## 5.3. If-Elseif-Else Statements

Unlike Python, which uses `elif`, MATLAB uses `elseif` to check for other conditions.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
if condition_1:
    # do code block 1
elif condition_2:
    # do code block 2
elif condition_3:
    # do code block 3
else:
    # do code block 4
# subsequent code
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
if condition_1
    % do code block 1 (indentation not required but recommended)
elseif condition_2
    % do code block 2 (indentation not required but recommended)
elseif condition_3
    % do code block 3 (indentation not required but recommended)
else
    % do code block 4 (indentation not required but recommended)
end
% subsequent code
```

## 5.4. Nested If Statements

When using nested if statements in MATLAB, each should have an `end` keyword.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
if condition_1: # outer if statement 
    # do code block 1
    if condition_2: # inner if statement 
        # do block code 2    
# subsequent code
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
if condition_1
    % do code block 1 (indentation not required but recommended)
    if condition_2
        % do code block 2 (indentation not required but recommended)
    end
end
% subsequent code
```

Notice that if you omit indentation in MATLAB, the code can become very difficult to read. For example, consider the code below with and without indentation.

$\mathbf{\color{orange}{\text{MATLAB (No Indentation):}}}$
```octave
if condition_1
% do code block 1
if condition_2
% do code block 2
else
% do code block 3
end
else
% do code block 4
end
% subsequent code
```

$\mathbf{\color{orange}{\text{MATLAB (With Indentation):}}}$
```octave
if condition_1
    % do code block 1
    if condition_2
        % do code block 2
    else
        % do code block 3
    end
else
    % do code block 4
end
% subsequent code
```

## 5.5. If Statements with Logical Operators

Similar to Python, we can use logical operators to combine multiple conditions.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
if condition_1 and condition_2: 
    # do code block 1
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
if condition_1 & condition_2 
    % do code block 1
end
```

<div class="alert alert-block alert-warning"> <b>NOTE!</b> Unlike Python, MATLAB does not have ternary operators.</div>

# 6. Iteration <a id="s6"></a>

Iteration works similarly in Python and MATLAB, but there are some differences in the syntax. Similar to conditional statements, no colon `:` should be included at the end of the line of a `for` or `while` loop. In addition, while indentation is not required in MATLAB, it is recommended for better readability. Lastly, you should use the keyword `end` to specify the end of a `for` or `while` block.

We saw that in Python we can loop over the values of a data structure, its indexes, both the values and indexes, among others. However, iteration in MATLAB is not as flexible. In MATLAB, you can either directly iterate over the elements or iterate over the indexes and then use indexing to access individual values in the sequence.

## 6.1. For Loops

In MATLAB, there is no `in` keyword that can be used with for loops. Instead, you would use an assignment operator `=`.

$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
for i in range(start, end, step): 
    # code block to be repeated
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```
for i = start:step:end 
    % code block to be repeated (indentation not required but recommended)
end
```

***

To iterate over all values in a sequence, the following syntax can be used:

$\mathbf{\color{midnightblue}{\text{Python (Iterating Over the Values):}}}$
```python
for value in sequence:
    # code block to be repeated, use value directly
```

$\mathbf{\color{orange}{\text{MATLAB (Iterating Over the Values):}}}$
```octave
for value = sequence
    % code block to be repeated, use value directly (indentation not required but recommended)
end
```

If `sequence` is a vector (i.e., 1D), you can iterate over the indexes using the following syntax:

$\mathbf{\color{midnightblue}{\text{Python (Using Indexing):}}}$
```python
for i in range(len(sequence)):
    # code block to be repeated, use sequence[i] for indexing
```

$\mathbf{\color{orange}{\text{MATLAB (Using Indexing):}}}$
```octave
for i = 1:length(sequence) % or for i = 1:numel(sequence)
    % code block to be repeated, use sequence(i) for indexing (indentation not required but recommended)
end
```

## 6.2. While loops


$\mathbf{\color{midnightblue}{\text{Python:}}}$
```python
while condition:
    # code block to be repeated
```

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
while condition
    % code block to be repeated (indentation not required but recommended)
end
```

## 6.3. Nested Loops

Similar to nested `if` statements, each loop within a nested loop should have an `end` keyword.

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
for index_1 = sequence_1
    for index_2 = sequence_2
        % code block to be repeated (indentation not required but recommended)
    end
end
```

## 6.4. Jump Statements: `break` and `continue`

Both `break` and `continue` have the same functionality in Python and MATLAB.

$\mathbf{\color{orange}{\text{MATLAB:}}}$
```octave
for index_1 = sequence_1
    if condition
        break % terminate the loop and skip to the subsequent code (indentation not required but recommended)
    end
end

% subsequent code

for index_1 = sequence_1
    if condition
        continue % skip to the next iteration in the loop (indentation not required but recommended)
    end
end
```

<div class="alert alert-block alert-warning"> <b>NOTE!</b> Unlike Python, MATLAB does not have list comprehensions.</div>